settings:
  files:
    outputs:
      status: false
      path: ""
      name: .r.outputs.log
    logs:
      status: false
      path: ""
      name: .r.logs.log
    errors:
      status: false
      path: ""
      name: .r.errors.log
  flimit: 10
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 3000
  host: "localhost"
schema:
- name: "API Rest Go"
  path: .
  commands:
    install:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /src
    ignored_paths:
    - .git
    - .realize
    - vendor
